- name: Cache Boost
  uses: actions/cache@v2
  with:
    path: '${{ runner.workspace }}/boost_*.tar.gz'
    key: 'boost-1.85.0'

- name: Build Boost
  # This won't re-download the archive unnecessarily:
  uses: egor-tensin/build-boost@v1
  with:
    version: 1.85.0
    libraries: align assert atomic config core predef preprocessor static_assert throw_exception type_traits
    platform: x64
    configuration: Release

- name: Show paths
  run: |
    printf 'Boost has been unpacked to: %s\n' '${{ steps.boost.outputs.root }}'
    printf 'Libraries can be found here: %s\n' '${{ steps.boost.outputs.librarydir }}'
  shell: bash
