name: testWindows

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update all submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.275.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, SPIRV-Cross, SPIRV-Tools, Glslang 
          vulkan-use-cache: true

      - name: Download glslangValidator
        run: curl -L -o glslang.zip https://github.com/KhronosGroup/glslang/releases/download/main-tot/glslang-master-windows-Release.zip

      - name: Extract glslangValidator
        shell: powershell
        run: Expand-Archive -Path glslang.zip -DestinationPath ${{github.workspace}}/glslang

      - name: Add glslangValidator to PATH
        run: echo "${{github.workspace}}/glslang/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
            boost_version: 1.84.0
            boost_install_dir: ${{github.workspace}}/boost
            platform_version: 2019
            toolset: msvc

      - name: Add Boost to PATH
        run: |
          echo "${{github.workspace}}/boost" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{github.workspace}}/boost/boost" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Cuda
        uses: Jimver/cuda-toolkit@v0.2.16
        id: cuda-toolkit
        with:
          cuda: '12.3.2'

      - name: Add Cuda to PATH
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          dir "${{steps.cuda-toolkit.outputs.CUDA_PATH}}/bin"
          nvcc -V
          echo "${{steps.cuda-toolkit.outputs.CUDA_PATH}}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{steps.cuda-toolkit.outputs.CUDA_PATH}}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$env:GITHUB_PATH"
          type $env:GITHUB_PATH

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DWERROR=YES -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCUDA_TOOLKIT_ROOT_DIR="${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

      - name: Build
        run: |
          type "${{github.workspace}}/build/CMakeCache.txt"
          echo "D:\a\rayx\rayx\vcpkg\installed\x64-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build/bin/release
        run: ./rayx-core-tst -x

      - name: CPack
        run: |
          cd ${{github.workspace}}/build
          cpack -G ZIP

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RAYX
          path: ${{github.workspace}}/build/RAYX-*.*.*-win64.zip
